### ISSUE TITLE
CoworkingDB Replacement

### ISSUE THREAD

**Issue by Gandalfounet** [jsayles/CoworkingDB#18]
Hello there,

I've recently built https://Networkup.io which has the same goal than CoworkingDB had. I'm currently adding all the Coworking Spaces and plan to convert it into an easy to use API Rest.

The goal is to help people to grow as entrepreneur by meeting influencers and build up a solid network. It includes coworking spaces, investors, incubators/accelerators, startups, events and so on. 

To join the network, sign up and complete your public profile. 

If you're looking for something specific, you're free to create ads. Also create projects if you have interesting ideas that require to build a team.

If you guys want to take a look at the project, you're welcome : [Networkup.io](https://networkup.io)

**Comment by jsayles** [comment]
Looks like this service is no longer available.
